import { imgLink } from "../components/imgLink.mjs";
import { htmlTpl } from "../templates/html.mjs";
import { mainTpl } from "../templates/main.mjs";

/** The front page of the website
 * @returns {string}
 */
export function genIndexPage() {
  return htmlTpl(/*html*/`
    <title>ANNAJA-PERSONAL OUTPUT</title>
    <link rel="stylesheet" href="gridstyle.css">
  `, mainTpl(/*html*/`
    <!-- this list should not be autogenerated from the picture list because elements are arranged manually -->
    <div id="myGallery" class="galleryOne galleryTwo galleryThree galleryFour galleryFive">
      ${imgLink("/images/1.jpg")}
      <div class="quotes item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/2.jpg")}
      ${imgLink("/images/3.jpg")}
      <div class="quotes__1 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/4.jpg")}
      ${imgLink("/images/5.jpg")}
      <div class="quotes__3 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/6.jpg")}
      ${imgLink("/images/7.jpg")}
      <div class="quotes__2 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/8.jpg")}
      ${imgLink("/images/9.jpg")}
      ${imgLink("/images/10.jpg")}
      <div class="quotes__1 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/11.jpg")}
      <div class="quotes item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/12.jpg")}
      <div class="quotes__1 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/13.jpg")}
      ${imgLink("/images/14.jpg")}
      ${imgLink("/images/19.jpg")}
      <div class="quotes__3 item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/15.jpg")}
      ${imgLink("/images/16.jpg")}
      ${imgLink("/images/17.jpg")}
      <div class="quotes item"><!-- <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut, fugit?</p> --></div>
      ${imgLink("/images/18.jpg")}
      ${imgLink("/images/19.jpg")}
    </div>
  `));
}